name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          color_snake: orange
          color_dots: white
          color_stroke: black
          color_bg: black
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: gif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
